version: '2'

services:

  postgres:
    image: postgres:11.1
    volumes:
    - ./dockerdatadev/psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'db_username'
      POSTGRES_PASSWORD: 'db_password'
      POSTGRES_DB: 'db_db'
    ports:
    - '5432:5432'