# Generated by Django 2.1.3 on 2018-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='color_hex',
            field=models.CharField(default='#000066', max_length=7),
        ),
    ]
